# Generated by Django 5.2.4 on 2025-07-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("viewer", "Viewer"),
                    ("customer", "Customer"),
                    ("manager", "Manager"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
